// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxwdzbdonwhcunjyttjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4d2R6YmRvbndoY3Vuanl0dGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTg1ODUsImV4cCI6MjA3MTQ3NDU4NX0.z_qhY-DftWgpG1I630tZ2GQB-B51r8aa891ZemRoiaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});